### PR TITLE
feat: support for complex and code fields

### PR DESCRIPTION
**Pull request by doojonio**

### CODE REVIEW

**Comment by mschout** [comment]
Hey, @doojonio thanks for making this pull request (with tests! woot!)

I'll take a look today.  Quick skim and it looks good I think

**Comment by avkhozov** [comment]
Hi @mschout, is there any chance to merge and release this feature in near future?

**Comment by doojonio** [comment]
@mschout Hi! I still want to use this feature in your module! How can we deal with it? I can change something, if you need

**Comment by mschout** [comment]
I just pushed this to CPAN as v0.57.. Usually takes a few hours for it to get indexed and propagate.

Sorry for the delay in getting to this.

**Pull request merged**
